// Generated by Tool/PacketGenerator/PacketGenerator.py. Do not edit directly.
#include "DungeonProtocol.h"

#include <NetServerSerializeBuffer.h>

namespace ActionRPG::DungeonProtocol
{
    ::PacketId DungeonChallenge::GetPacketId() const
    {
        return static_cast<::PacketId>(PacketType::DUNGEON_CHALLENGE);
    }

    void DungeonChallenge::BufferToPacket(NetBuffer& inBuffer)
    {
        inBuffer >> challenge;
    }

    void DungeonChallenge::PacketToBuffer(NetBuffer& outBuffer)
    {
        outBuffer << challenge;
    }

    ::PacketId DungeonAuthResult::GetPacketId() const
    {
        return static_cast<::PacketId>(PacketType::DUNGEON_AUTH_RESULT);
    }

    void DungeonAuthResult::BufferToPacket(NetBuffer& inBuffer)
    {
        inBuffer >> succeeded;
    }

    void DungeonAuthResult::PacketToBuffer(NetBuffer& outBuffer)
    {
        outBuffer << succeeded;
    }

    void RegisterPackets()
    {
        PacketManager::GetInst().RegisterPacket<DungeonChallenge>();
        PacketManager::GetInst().RegisterPacket<DungeonAuthResult>();
    }
}
