// Generated by Tool/PacketGenerator/PacketGenerator.py. Do not edit directly.
#include "DungeonProtocol.h"

#include <NetServerSerializeBuffer.h>

namespace ActionRPG::DungeonProtocol
{
    ::PacketId DungeonChallenge::GetPacketId() const
    {
        return static_cast<::PacketId>(PacketType::DUNGEON_CHALLENGE);
    }

    void DungeonChallenge::BufferToPacket(NetBuffer& inBuffer)
    {
        inBuffer >> challenge;
    }

    void DungeonChallenge::PacketToBuffer(NetBuffer& outBuffer)
    {
        outBuffer << challenge;
    }

    ::PacketId DungeonAuthResult::GetPacketId() const
    {
        return static_cast<::PacketId>(PacketType::DUNGEON_AUTH_RESULT);
    }

    void DungeonAuthResult::BufferToPacket(NetBuffer& inBuffer)
    {
        inBuffer >> succeeded;
    }

    void DungeonAuthResult::PacketToBuffer(NetBuffer& outBuffer)
    {
        outBuffer << succeeded;
    }

    ::PacketId DungeonWorldRequest::GetPacketId() const
    {
        return static_cast<::PacketId>(PacketType::DUNGEON_WORLD_REQUEST);
    }

    void DungeonWorldRequest::BufferToPacket(NetBuffer& inBuffer)
    {
        inBuffer >> offset;
    }

    void DungeonWorldRequest::PacketToBuffer(NetBuffer& outBuffer)
    {
        outBuffer << offset;
    }

    ::PacketId DungeonWorldChunk::GetPacketId() const
    {
        return static_cast<::PacketId>(PacketType::DUNGEON_WORLD_CHUNK);
    }

    void DungeonWorldChunk::BufferToPacket(NetBuffer& inBuffer)
    {
        inBuffer >> totalBytes;
        inBuffer >> offset;
        inBuffer >> payload;
    }

    void DungeonWorldChunk::PacketToBuffer(NetBuffer& outBuffer)
    {
        outBuffer << totalBytes;
        outBuffer << offset;
        outBuffer << payload;
    }

    ::PacketId DungeonMoveInput::GetPacketId() const
    {
        return static_cast<::PacketId>(PacketType::DUNGEON_MOVE_INPUT);
    }

    void DungeonMoveInput::BufferToPacket(NetBuffer& inBuffer)
    {
        inBuffer >> sequence;
        inBuffer >> directionX;
        inBuffer >> directionY;
        inBuffer >> running;
    }

    void DungeonMoveInput::PacketToBuffer(NetBuffer& outBuffer)
    {
        outBuffer << sequence;
        outBuffer << directionX;
        outBuffer << directionY;
        outBuffer << running;
    }

    ::PacketId DungeonPlayerState::GetPacketId() const
    {
        return static_cast<::PacketId>(PacketType::DUNGEON_PLAYER_STATE);
    }

    void DungeonPlayerState::BufferToPacket(NetBuffer& inBuffer)
    {
        inBuffer >> sequence;
        inBuffer >> mapId;
        inBuffer >> x;
        inBuffer >> y;
    }

    void DungeonPlayerState::PacketToBuffer(NetBuffer& outBuffer)
    {
        outBuffer << sequence;
        outBuffer << mapId;
        outBuffer << x;
        outBuffer << y;
    }

    ::PacketId DungeonActionInput::GetPacketId() const
    {
        return static_cast<::PacketId>(PacketType::DUNGEON_ACTION_INPUT);
    }

    void DungeonActionInput::BufferToPacket(NetBuffer& inBuffer)
    {
        inBuffer >> sequence;
        inBuffer >> action;
        inBuffer >> facingLeft;
    }

    void DungeonActionInput::PacketToBuffer(NetBuffer& outBuffer)
    {
        outBuffer << sequence;
        outBuffer << action;
        outBuffer << facingLeft;
    }

    ::PacketId DungeonActionResult::GetPacketId() const
    {
        return static_cast<::PacketId>(PacketType::DUNGEON_ACTION_RESULT);
    }

    void DungeonActionResult::BufferToPacket(NetBuffer& inBuffer)
    {
        inBuffer >> sequence;
        inBuffer >> accepted;
        inBuffer >> serverTick;
    }

    void DungeonActionResult::PacketToBuffer(NetBuffer& outBuffer)
    {
        outBuffer << sequence;
        outBuffer << accepted;
        outBuffer << serverTick;
    }

    ::PacketId DungeonCombatStateRequest::GetPacketId() const
    {
        return static_cast<::PacketId>(PacketType::DUNGEON_COMBAT_STATE_REQUEST);
    }

    void DungeonCombatStateRequest::BufferToPacket(NetBuffer& inBuffer)
    {
        inBuffer >> snapshotId;
        inBuffer >> offset;
    }

    void DungeonCombatStateRequest::PacketToBuffer(NetBuffer& outBuffer)
    {
        outBuffer << snapshotId;
        outBuffer << offset;
    }

    ::PacketId DungeonCombatStateChunk::GetPacketId() const
    {
        return static_cast<::PacketId>(PacketType::DUNGEON_COMBAT_STATE_CHUNK);
    }

    void DungeonCombatStateChunk::BufferToPacket(NetBuffer& inBuffer)
    {
        inBuffer >> snapshotId;
        inBuffer >> totalBytes;
        inBuffer >> offset;
        inBuffer >> status;
        inBuffer >> retryAfterMs;
        inBuffer >> payload;
    }

    void DungeonCombatStateChunk::PacketToBuffer(NetBuffer& outBuffer)
    {
        outBuffer << snapshotId;
        outBuffer << totalBytes;
        outBuffer << offset;
        outBuffer << status;
        outBuffer << retryAfterMs;
        outBuffer << payload;
    }

    void RegisterPackets()
    {
        PacketManager::GetInst().RegisterPacket<DungeonChallenge>();
        PacketManager::GetInst().RegisterPacket<DungeonAuthResult>();
        PacketManager::GetInst().RegisterPacket<DungeonWorldRequest>();
        PacketManager::GetInst().RegisterPacket<DungeonWorldChunk>();
        PacketManager::GetInst().RegisterPacket<DungeonMoveInput>();
        PacketManager::GetInst().RegisterPacket<DungeonPlayerState>();
        PacketManager::GetInst().RegisterPacket<DungeonActionInput>();
        PacketManager::GetInst().RegisterPacket<DungeonActionResult>();
        PacketManager::GetInst().RegisterPacket<DungeonCombatStateRequest>();
        PacketManager::GetInst().RegisterPacket<DungeonCombatStateChunk>();
    }
}
