#pragma once

// Generated by Tool/PacketGenerator/PacketGenerator.py. Do not edit directly.
#include "RudpPrerequisites.h"

#include <cstdint>

#include <PacketManager.h>

namespace ActionRPG::DungeonProtocol
{
    enum class PacketType : ::PacketId
    {
        INVALID_PACKET_ID = 0,
        DUNGEON_CHALLENGE,
        DUNGEON_AUTH_RESULT,
        DUNGEON_WORLD_REQUEST,
        DUNGEON_WORLD_CHUNK,
        DUNGEON_MOVE_INPUT,
        DUNGEON_PLAYER_STATE,
        DUNGEON_ACTION_INPUT,
        DUNGEON_ACTION_RESULT,
        DUNGEON_COMBAT_STATE_REQUEST,
        DUNGEON_COMBAT_STATE_CHUNK,
    };

    class DungeonChallenge final : public IPacket
    {
    public:
        [[nodiscard]] ::PacketId GetPacketId() const override;
        void BufferToPacket(NetBuffer& inBuffer) override;
        void PacketToBuffer(NetBuffer& outBuffer) override;

        std::uint64_t challenge{};
    };

    class DungeonAuthResult final : public IPacket
    {
    public:
        [[nodiscard]] ::PacketId GetPacketId() const override;
        void BufferToPacket(NetBuffer& inBuffer) override;
        void PacketToBuffer(NetBuffer& outBuffer) override;

        std::uint8_t succeeded{};
    };

    class DungeonWorldRequest final : public IPacket
    {
    public:
        [[nodiscard]] ::PacketId GetPacketId() const override;
        void BufferToPacket(NetBuffer& inBuffer) override;
        void PacketToBuffer(NetBuffer& outBuffer) override;

        std::uint32_t offset{};
    };

    class DungeonWorldChunk final : public IPacket
    {
    public:
        [[nodiscard]] ::PacketId GetPacketId() const override;
        void BufferToPacket(NetBuffer& inBuffer) override;
        void PacketToBuffer(NetBuffer& outBuffer) override;

        std::uint32_t totalBytes{};
        std::uint32_t offset{};
        std::string payload{};
    };

    class DungeonMoveInput final : public IPacket
    {
    public:
        [[nodiscard]] ::PacketId GetPacketId() const override;
        void BufferToPacket(NetBuffer& inBuffer) override;
        void PacketToBuffer(NetBuffer& outBuffer) override;

        std::uint32_t sequence{};
        std::int8_t directionX{};
        std::int8_t directionY{};
        std::uint8_t running{};
    };

    class DungeonPlayerState final : public IPacket
    {
    public:
        [[nodiscard]] ::PacketId GetPacketId() const override;
        void BufferToPacket(NetBuffer& inBuffer) override;
        void PacketToBuffer(NetBuffer& outBuffer) override;

        std::uint32_t sequence{};
        std::string mapId{};
        float x{};
        float y{};
    };

    class DungeonActionInput final : public IPacket
    {
    public:
        [[nodiscard]] ::PacketId GetPacketId() const override;
        void BufferToPacket(NetBuffer& inBuffer) override;
        void PacketToBuffer(NetBuffer& outBuffer) override;

        std::uint32_t sequence{};
        std::uint8_t action{};
        std::uint8_t facingLeft{};
    };

    class DungeonActionResult final : public IPacket
    {
    public:
        [[nodiscard]] ::PacketId GetPacketId() const override;
        void BufferToPacket(NetBuffer& inBuffer) override;
        void PacketToBuffer(NetBuffer& outBuffer) override;

        std::uint32_t sequence{};
        std::uint8_t accepted{};
        std::uint64_t serverTick{};
    };

    class DungeonCombatStateRequest final : public IPacket
    {
    public:
        [[nodiscard]] ::PacketId GetPacketId() const override;
        void BufferToPacket(NetBuffer& inBuffer) override;
        void PacketToBuffer(NetBuffer& outBuffer) override;

        std::uint32_t snapshotId{};
        std::uint32_t offset{};
    };

    class DungeonCombatStateChunk final : public IPacket
    {
    public:
        [[nodiscard]] ::PacketId GetPacketId() const override;
        void BufferToPacket(NetBuffer& inBuffer) override;
        void PacketToBuffer(NetBuffer& outBuffer) override;

        std::uint32_t snapshotId{};
        std::uint32_t totalBytes{};
        std::uint32_t offset{};
        std::uint8_t status{};
        std::uint32_t retryAfterMs{};
        std::string payload{};
    };

    void RegisterPackets();
}
