#pragma once

// Generated by Tool/PacketGenerator/PacketGenerator.py. Do not edit directly.
#include "RudpPrerequisites.h"

#include <cstdint>

#include <PacketManager.h>

namespace ActionRPG::DungeonProtocol
{
    enum class PacketType : ::PacketId
    {
        INVALID_PACKET_ID = 0,
        DUNGEON_CHALLENGE,
        DUNGEON_AUTH_RESULT,
    };

    class DungeonChallenge final : public IPacket
    {
    public:
        [[nodiscard]] ::PacketId GetPacketId() const override;
        void BufferToPacket(NetBuffer& inBuffer) override;
        void PacketToBuffer(NetBuffer& outBuffer) override;

        std::uint64_t challenge{};
    };

    class DungeonAuthResult final : public IPacket
    {
    public:
        [[nodiscard]] ::PacketId GetPacketId() const override;
        void BufferToPacket(NetBuffer& inBuffer) override;
        void PacketToBuffer(NetBuffer& outBuffer) override;

        std::uint8_t succeeded{};
    };

    void RegisterPackets();
}
