#pragma once

// Generated by Tool/PacketGenerator/PacketGenerator.py. Do not edit directly.
#include <cstdint>
#include <string>
#include <vector>

namespace TownProtocol
{
    enum class PacketType : std::uint16_t
    {
        EnterTownRequest = 1,
        EnterTownResponse = 2,
        MoveInput = 3,
        PlayerAppear = 4,
        PlayerMove = 5,
        PlayerDisappear = 6,
        ConfirmDungeonJoin = 7,
        EnterDungeonRequest = 8,
        EnterDungeonResponse = 9,
        MapChanged = 10,
        DungeonSelectionOpen = 11,
        PartyInviteRequest = 12,
        PartyInviteAnswer = 13,
        PartyLeaveRequest = 14,
        PartyKickRequest = 15,
        PartyInvitation = 16,
        PartySnapshot = 17,
        PartyOperationResult = 18,
        PartySettingsRequest = 19,
        PartyDirectoryPageRequest = 20,
        PartyDirectoryUnsubscribe = 21,
        PartyDirectoryPage = 22,
        PartyDirectoryChanged = 23,
        PartyCreateRequest = 24,
    };

    struct EnterTownRequest
    {
        std::string playerName{};
        std::uint32_t characterId{};
    };

    struct EnterTownResponse
    {
        std::uint64_t playerId{};
        std::uint32_t characterId{};
        MapInfo map{};
    };

    struct MoveInput
    {
        std::uint32_t sequence{};
        std::int8_t directionX{};
        std::int8_t directionY{};
        bool running{};
    };

    struct PlayerAppear
    {
        std::uint64_t playerId{};
        std::string playerName{};
        std::uint32_t characterId{};
        Vector2 position{};
        Vector2 velocity{};
    };

    struct PlayerMove
    {
        std::uint64_t playerId{};
        std::uint32_t serverTick{};
        std::uint32_t lastProcessedInput{};
        Vector2 position{};
        Vector2 velocity{};
    };

    struct PlayerDisappear
    {
        std::uint64_t playerId{};
    };

    struct ConfirmDungeonJoin
    {
        std::uint64_t roomId{};
        std::uint64_t challenge{};
    };

    struct EnterDungeonRequest
    {
        std::string zoneId{};
        std::uint32_t dungeonId{};
    };

    struct EnterDungeonResponse
    {
        bool succeeded{};
        std::uint64_t roomId{};
        std::uint64_t combatSeed{};
        std::string sessionBrokerAddress{};
        std::uint16_t sessionBrokerPort{};
    };

    struct MapChanged
    {
        MapInfo map{};
        Vector2 position{};
    };

    struct DungeonSelectionOpen
    {
        std::string zoneId{};
        std::string dungeonGroupId{};
        std::vector<DungeonOption> dungeons{};
    };

    struct PartyInviteRequest
    {
        std::uint64_t targetPlayerId{};
    };

    struct PartyInviteAnswer
    {
        std::uint64_t invitationId{};
        bool accepted{};
    };

    struct PartyLeaveRequest
    {
    };

    struct PartyKickRequest
    {
        std::uint64_t targetPlayerId{};
    };

    struct PartyInvitation
    {
        std::uint64_t invitationId{};
        std::uint64_t inviterPlayerId{};
        std::string inviterName{};
    };

    struct PartySnapshot
    {
        std::uint64_t partyId{};
        std::uint64_t leaderPlayerId{};
        std::vector<PartyMemberInfo> members{};
        std::string title{};
        bool isPublic{};
    };

    struct PartyOperationResult
    {
        PartyOperationType operation{};
        PartyResultCode result{};
    };

    struct PartySettingsRequest
    {
        std::string title{};
        bool isPublic{};
    };

    struct PartyDirectoryPageRequest
    {
        std::uint32_t page{};
    };

    struct PartyDirectoryUnsubscribe
    {
    };

    struct PartyDirectoryPage
    {
        std::uint32_t page{};
        std::uint32_t totalPages{};
        std::uint32_t totalCount{};
        std::uint64_t revision{};
        std::vector<PartyDirectoryEntry> parties{};
    };

    struct PartyDirectoryChanged
    {
        std::uint64_t revision{};
    };

    struct PartyCreateRequest
    {
        std::string title{};
        bool isPublic{};
    };

}
