#pragma once

// Generated by Tool/PacketGenerator/PacketGenerator.py. Do not edit directly.
#include <cstdint>
#include <string>
#include <vector>

namespace TownProtocol
{
    enum class PacketType : std::uint16_t
    {
        EnterTownRequest = 1,
        EnterTownResponse = 2,
        MoveInput = 3,
        PlayerAppear = 4,
        PlayerMove = 5,
        PlayerDisappear = 6,
        ConfirmDungeonJoin = 7,
        EnterDungeonRequest = 8,
        EnterDungeonResponse = 9,
        MapChanged = 10,
        DungeonSelectionOpen = 11,
    };

    struct EnterTownRequest
    {
        std::string playerName{};
        std::uint32_t characterId{};
    };

    struct EnterTownResponse
    {
        std::uint64_t playerId{};
        std::uint32_t characterId{};
        MapInfo map{};
    };

    struct MoveInput
    {
        std::uint32_t sequence{};
        std::int8_t directionX{};
        std::int8_t directionY{};
        bool running{};
    };

    struct PlayerAppear
    {
        std::uint64_t playerId{};
        std::string playerName{};
        std::uint32_t characterId{};
        Vector2 position{};
        Vector2 velocity{};
    };

    struct PlayerMove
    {
        std::uint64_t playerId{};
        std::uint32_t serverTick{};
        std::uint32_t lastProcessedInput{};
        Vector2 position{};
        Vector2 velocity{};
    };

    struct PlayerDisappear
    {
        std::uint64_t playerId{};
    };

    struct ConfirmDungeonJoin
    {
        std::uint64_t roomId{};
        std::uint64_t challenge{};
    };

    struct EnterDungeonRequest
    {
        std::string zoneId{};
        std::uint32_t dungeonId{};
    };

    struct EnterDungeonResponse
    {
        bool succeeded{};
        std::uint64_t roomId{};
        std::uint64_t combatSeed{};
        std::string sessionBrokerAddress{};
        std::uint16_t sessionBrokerPort{};
    };

    struct MapChanged
    {
        MapInfo map{};
        Vector2 position{};
    };

    struct DungeonSelectionOpen
    {
        std::string zoneId{};
        std::string dungeonGroupId{};
        std::vector<DungeonOption> dungeons{};
    };

}
