#pragma once

// Generated by Tool/PacketGenerator/PacketGenerator.py. Do not edit directly.
#include <cstdint>
#include <string>
#include <vector>

namespace TownProtocol
{
    enum class PacketType : std::uint16_t
    {
        EnterTownRequest = 1,
        EnterTownResponse = 2,
        MoveInput = 3,
        PlayerAppear = 4,
        PlayerMove = 5,
        PlayerDisappear = 6,
        ConfirmDungeonJoin = 7,
        EnterDungeonRequest = 8,
        EnterDungeonResponse = 9,
        MapChanged = 10,
        DungeonSelectionOpen = 11,
        PartyInviteRequest = 12,
        PartyInviteAnswer = 13,
        PartyLeaveRequest = 14,
        PartyKickRequest = 15,
        PartyInvitation = 16,
        PartySnapshot = 17,
        PartyOperationResult = 18,
        PartySettingsRequest = 19,
        PartyDirectoryPageRequest = 20,
        PartyDirectoryUnsubscribe = 21,
        PartyDirectoryPage = 22,
        PartyDirectoryChanged = 23,
        PartyCreateRequest = 24,
        DungeonCompletionRequest = 25,
        DungeonCompletionResponse = 26,
        SkillStateRequest = 27,
        LearnSkillRequest = 28,
        SkillStateResponse = 29,
        PartyDetailRequest = 30,
        PartyDetailResponse = 31,
        PartyJoinRequest = 32,
        PartyJoinAnswer = 33,
        PartyJoinRequestUpdate = 34,
        PartyKicked = 35,
        AdmissionTicketRequest = 36,
        AdmissionResult = 37,
        CharacterListRequest = 38,
        CharacterListResponse = 39,
        CharacterCreateRequest = 40,
        CharacterCreateResponse = 41,
        CharacterSelectRequest = 42,
        CharacterSelectResponse = 43,
        InventoryStateRequest = 44,
        InventoryStateResponse = 45,
        InventoryOperationRequest = 46,
        InventoryOperationResponse = 47,
        ItemDefinitionsResponse = 48,
    };

    struct EnterTownRequest
    {
        std::string playerName{};
        std::uint32_t characterId{};
    };

    struct EnterTownResponse
    {
        std::uint64_t playerId{};
        std::uint32_t characterId{};
        MapInfo map{};
    };

    struct MoveInput
    {
        std::uint32_t sequence{};
        std::int8_t directionX{};
        std::int8_t directionY{};
        bool running{};
    };

    struct PlayerAppear
    {
        std::uint64_t playerId{};
        std::string playerName{};
        std::uint32_t characterId{};
        Vector2 position{};
        Vector2 velocity{};
    };

    struct PlayerMove
    {
        std::uint64_t playerId{};
        std::uint32_t serverTick{};
        std::uint32_t lastProcessedInput{};
        Vector2 position{};
        Vector2 velocity{};
    };

    struct PlayerDisappear
    {
        std::uint64_t playerId{};
    };

    struct ConfirmDungeonJoin
    {
        std::uint64_t roomId{};
        std::uint64_t challenge{};
    };

    struct EnterDungeonRequest
    {
        std::string zoneId{};
        std::uint32_t dungeonId{};
    };

    struct EnterDungeonResponse
    {
        bool succeeded{};
        std::uint64_t roomId{};
        std::uint64_t combatSeed{};
        std::string sessionBrokerAddress{};
        std::uint16_t sessionBrokerPort{};
    };

    struct MapChanged
    {
        MapInfo map{};
        Vector2 position{};
    };

    struct DungeonSelectionOpen
    {
        std::string zoneId{};
        std::string dungeonGroupId{};
        std::vector<DungeonOption> dungeons{};
    };

    struct PartyInviteRequest
    {
        std::uint64_t targetPlayerId{};
    };

    struct PartyInviteAnswer
    {
        std::uint64_t invitationId{};
        bool accepted{};
    };

    struct PartyLeaveRequest
    {
    };

    struct PartyKickRequest
    {
        std::uint64_t targetPlayerId{};
    };

    struct PartyInvitation
    {
        std::uint64_t invitationId{};
        std::uint64_t inviterPlayerId{};
        std::string inviterName{};
    };

    struct PartySnapshot
    {
        std::uint64_t partyId{};
        std::uint64_t leaderPlayerId{};
        std::vector<PartyMemberInfo> members{};
        std::string title{};
        bool isPublic{};
    };

    struct PartyOperationResult
    {
        PartyOperationType operation{};
        PartyResultCode result{};
    };

    struct PartySettingsRequest
    {
        std::string title{};
        bool isPublic{};
    };

    struct PartyDirectoryPageRequest
    {
        std::uint32_t page{};
    };

    struct PartyDirectoryUnsubscribe
    {
    };

    struct PartyDirectoryPage
    {
        std::uint32_t page{};
        std::uint32_t totalPages{};
        std::uint32_t totalCount{};
        std::uint64_t revision{};
        std::vector<PartyDirectoryEntry> parties{};
    };

    struct PartyDirectoryChanged
    {
        std::uint64_t revision{};
    };

    struct PartyCreateRequest
    {
        std::string title{};
        bool isPublic{};
    };

    struct DungeonCompletionRequest
    {
        std::uint64_t roomId{};
        bool retry{};
    };

    struct DungeonCompletionResponse
    {
        std::uint64_t previousRoomId{};
        bool succeeded{};
        bool retry{};
        std::uint64_t roomId{};
        std::uint64_t combatSeed{};
        std::string sessionBrokerAddress{};
        std::uint16_t sessionBrokerPort{};
    };

    struct SkillStateRequest
    {
    };

    struct LearnSkillRequest
    {
        std::string skillId{};
        std::uint32_t expectedSkillLevel{};
    };

    struct SkillStateResponse
    {
        std::string payload{};
    };

    struct PartyDetailRequest
    {
        std::uint64_t partyId{};
    };

    struct PartyDetailResponse
    {
        std::uint64_t partyId{};
        PartyResultCode result{};
        std::string title{};
        std::uint64_t leaderPlayerId{};
        bool isPublic{};
        bool busy{};
        std::vector<PartyMemberInfo> members{};
    };

    struct PartyJoinRequest
    {
        std::uint64_t partyId{};
    };

    struct PartyJoinAnswer
    {
        std::uint64_t requestId{};
        bool accepted{};
    };

    struct PartyJoinRequestUpdate
    {
        std::uint64_t requestId{};
        std::uint64_t partyId{};
        std::uint64_t requesterPlayerId{};
        std::string requesterName{};
        PartyJoinRequestState state{};
        PartyResultCode result{};
    };

    struct PartyKicked
    {
        std::uint64_t partyId{};
        std::uint64_t leaderPlayerId{};
    };

    struct AdmissionTicketRequest
    {
        std::string ticket{};
    };

    struct AdmissionResult
    {
        std::uint8_t result{};
    };

    struct CharacterListRequest
    {
        std::string json{};
    };

    struct CharacterListResponse
    {
        std::string json{};
    };

    struct CharacterCreateRequest
    {
        std::string json{};
    };

    struct CharacterCreateResponse
    {
        std::string json{};
    };

    struct CharacterSelectRequest
    {
        std::string json{};
    };

    struct CharacterSelectResponse
    {
        std::string json{};
    };

    struct InventoryStateRequest
    {
        std::string json{};
    };

    struct InventoryStateResponse
    {
        std::string json{};
    };

    struct InventoryOperationRequest
    {
        std::string json{};
    };

    struct InventoryOperationResponse
    {
        std::string json{};
    };

    struct ItemDefinitionsResponse
    {
        std::string json{};
    };

}
