"""Generate shared RUDP packet classes from Tool/PacketDefine.yml."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import re
import sys
import tempfile

import yaml

from PacketSchema import SCALARS, STRINGS, ValidateSchema


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SCHEMA = PROJECT_ROOT / "Tool" / "PacketDefine.yml"
SUPPORTED_FIELD_TYPES = SCALARS | STRINGS


def ToEnumName(inName: str) -> str:
    firstPass = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", inName)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", firstPass).upper()


def LoadDefinition(inSchemaPath: Path) -> tuple[dict, list[dict]]:
    data = yaml.safe_load(inSchemaPath.read_text(encoding="utf-8-sig"))
    if not isinstance(data, dict):
        raise ValueError("YAML root must be a mapping")

    protocol = data.get("Protocol")
    if not isinstance(protocol, dict):
        raise ValueError("Protocol configuration is required")

    packets, structs = ValidateSchema(data)
    if structs:
        raise ValueError("The current MultiSocketRUDP serializer does not support generated structs")
    for packet in packets:
        if "Id" in packet:
            raise ValueError("Packet IDs are assigned by YAML list order; do not specify Id")
        for item in packet["Items"]:
            if item["Type"] not in SUPPORTED_FIELD_TYPES:
                raise ValueError(
                    f"{packet['PacketName']}.{item['Name']}: unsupported wire type {item['Type']}"
                )

    namespace = protocol.get("Namespace")
    packetIdEnum = protocol.get("PacketIdEnum", "PacketType")
    registerFunction = protocol.get("RegisterFunction", "RegisterPackets")
    targets = protocol.get("Targets")
    if not isinstance(namespace, str) or not re.fullmatch(
        r"[A-Za-z][A-Za-z_0-9]*(?:::[A-Za-z][A-Za-z_0-9]*)*", namespace
    ):
        raise ValueError("Protocol.Namespace is invalid")
    for name, value in (
        ("Protocol.PacketIdEnum", packetIdEnum),
        ("Protocol.RegisterFunction", registerFunction),
    ):
        if not isinstance(value, str) or not re.fullmatch(r"[A-Za-z][A-Za-z_0-9]*", value):
            raise ValueError(f"{name} is invalid")
    if not isinstance(targets, list) or not targets:
        raise ValueError("Protocol.Targets must contain at least one output target")

    normalizedTargets = []
    for target in targets:
        if not isinstance(target, dict):
            raise ValueError("Each Protocol.Targets entry must be a mapping")
        header = target.get("Header")
        source = target.get("Source")
        prerequisite = target.get("PrerequisiteHeader")
        if not all(isinstance(value, str) and value for value in (header, source, prerequisite)):
            raise ValueError("Each target requires Header, Source, and PrerequisiteHeader")
        normalizedTargets.append(
            {
                "Header": header,
                "Source": source,
                "PrerequisiteHeader": prerequisite,
            }
        )

    return {
        "Namespace": namespace,
        "PacketIdEnum": packetIdEnum,
        "RegisterFunction": registerFunction,
        "Targets": normalizedTargets,
    }, packets


def RenderHeader(inProtocol: dict, inPackets: list[dict], inPrerequisiteHeader: str) -> str:
    packetIdEnum = inProtocol["PacketIdEnum"]
    lines = [
        "#pragma once",
        "",
        "// Generated by Tool/PacketGenerator/PacketGenerator.py. Do not edit directly.",
        f'#include "{inPrerequisiteHeader}"',
        "",
        "#include <cstdint>",
        "",
        "#include <PacketManager.h>",
        "",
        f"namespace {inProtocol['Namespace']}",
        "{",
        f"    enum class {packetIdEnum} : ::PacketId",
        "    {",
        "        INVALID_PACKET_ID = 0,",
    ]
    for packet in inPackets:
        lines.append(f"        {ToEnumName(packet['PacketName'])},")
    lines.extend(["    };", ""])

    for packet in inPackets:
        packetName = packet["PacketName"]
        items = packet["Items"]
        lines.extend(
            [
                f"    class {packetName} final : public IPacket",
                "    {",
                "    public:",
                "        [[nodiscard]] ::PacketId GetPacketId() const override;",
            ]
        )
        if items:
            lines.extend(
                [
                    "        void BufferToPacket(NetBuffer& inBuffer) override;",
                    "        void PacketToBuffer(NetBuffer& outBuffer) override;",
                    "",
                ]
            )
            lines.extend(f"        {item['Type']} {item['Name']}{{}};" for item in items)
        lines.extend(["    };", ""])

    lines.extend([f"    void {inProtocol['RegisterFunction']}();", "}", ""])
    return "\n".join(lines)


def RenderSource(inProtocol: dict, inPackets: list[dict], inHeaderName: str) -> str:
    packetIdEnum = inProtocol["PacketIdEnum"]
    lines = [
        "// Generated by Tool/PacketGenerator/PacketGenerator.py. Do not edit directly.",
        f'#include "{inHeaderName}"',
        "",
        "#include <NetServerSerializeBuffer.h>",
        "",
        f"namespace {inProtocol['Namespace']}",
        "{",
    ]

    for packet in inPackets:
        packetName = packet["PacketName"]
        items = packet["Items"]
        lines.extend(
            [
                f"    ::PacketId {packetName}::GetPacketId() const",
                "    {",
                f"        return static_cast<::PacketId>({packetIdEnum}::{ToEnumName(packetName)});",
                "    }",
                "",
            ]
        )
        if items:
            lines.extend(
                [
                    f"    void {packetName}::BufferToPacket(NetBuffer& inBuffer)",
                    "    {",
                ]
            )
            lines.extend(f"        inBuffer >> {item['Name']};" for item in items)
            lines.extend(["    }", "", f"    void {packetName}::PacketToBuffer(NetBuffer& outBuffer)", "    {"])
            lines.extend(f"        outBuffer << {item['Name']};" for item in items)
            lines.extend(["    }", ""])

    lines.extend([f"    void {inProtocol['RegisterFunction']}()", "    {"])
    lines.extend(
        f"        PacketManager::GetInst().RegisterPacket<{packet['PacketName']}>();"
        for packet in inPackets
    )
    lines.extend(["    }", "}", ""])
    return "\n".join(lines)


def ResolveOutput(inRelativePath: str) -> Path:
    projectRoot = Path(os.path.abspath(PROJECT_ROOT))
    output = Path(os.path.abspath(projectRoot / inRelativePath))
    commonPath = os.path.commonpath((projectRoot, output))
    if os.path.normcase(commonPath) != os.path.normcase(str(projectRoot)):
        raise ValueError(f"Output path escapes the project: {inRelativePath}")
    return output


def BuildOutputs(inProtocol: dict, inPackets: list[dict]) -> dict[Path, str]:
    outputs = {}
    for target in inProtocol["Targets"]:
        headerPath = ResolveOutput(target["Header"])
        sourcePath = ResolveOutput(target["Source"])
        outputs[headerPath] = RenderHeader(inProtocol, inPackets, target["PrerequisiteHeader"])
        outputs[sourcePath] = RenderSource(inProtocol, inPackets, headerPath.name)
    return outputs


def WriteOutputs(inOutputs: dict[Path, str], inCheck: bool) -> bool:
    changed = {
        path: content
        for path, content in inOutputs.items()
        if not path.exists() or path.read_text(encoding="utf-8-sig") != content
    }
    if inCheck:
        for path in changed:
            print(f"Out of date: {path.relative_to(PROJECT_ROOT).as_posix()}")
        return not changed

    temporaryFiles = {}
    try:
        for path, content in changed.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as stream:
                stream.write(content.encode("utf-8"))
                temporaryFiles[path] = Path(stream.name)
        for path, temporaryPath in temporaryFiles.items():
            os.replace(temporaryPath, path)
    finally:
        for temporaryPath in temporaryFiles.values():
            temporaryPath.unlink(missing_ok=True)

    print(f"Generated RUDP protocol: {len(changed)} changed files.")
    return True


def Generate(inSchemaPath: Path = DEFAULT_SCHEMA, inCheck: bool = False) -> bool:
    protocol, packets = LoadDefinition(inSchemaPath)
    return WriteOutputs(BuildOutputs(protocol, packets), inCheck)


def Main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schema", type=Path, default=DEFAULT_SCHEMA)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        return 0 if Generate(args.schema.resolve(), args.check) else 1
    except (OSError, ValueError, TypeError, KeyError, yaml.YAMLError) as error:
        print(f"Packet generation failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(Main())
